/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#4ECDC4",
          foreground: "#FFFFFF",
          50: "#E6F9F8",
          100: "#CCF3F1",
          200: "#99E7E3",
          300: "#66DBD5",
          400: "#4ECDC4",
          500: "#3DBDB4",
          600: "#2A9D95",
          700: "#1F7D77",
          800: "#155D59",
          900: "#0B3D3A",
        },
        secondary: {
          DEFAULT: "#FF6B6B",
          foreground: "#FFFFFF",
          50: "#FFF0F0",
          100: "#FFE1E1",
          200: "#FFC3C3",
          300: "#FFA5A5",
          400: "#FF6B6B",
          500: "#FF4C4C",
          600: "#FF2D2D",
          700: "#CC2424",
          800: "#991B1B",
          900: "#661212",
        },
        accent: {
          DEFAULT: "#FFE66D",
          foreground: "#2C3E50",
          50: "#FFFBE6",
          100: "#FFF7CC",
          200: "#FFEF99",
          300: "#FFE76D",
          400: "#FFE66D",
          500: "#FFD93D",
          600: "#FFCC00",
          700: "#CCA300",
          800: "#997A00",
          900: "#665200",
        },
        dark: {
          DEFAULT: "#2C3E50",
          foreground: "#F7F9FC",
          50: "#E8EBEE",
          100: "#D1D7DD",
          200: "#A3AFBB",
          300: "#758799",
          400: "#475F77",
          500: "#2C3E50",
          600: "#233240",
          700: "#1A2630",
          800: "#111920",
          900: "#080D10",
        },
        light: {
          DEFAULT: "#F7F9FC",
          foreground: "#2C3E50",
          50: "#FFFFFF",
          100: "#F7F9FC",
          200: "#EFF3F7",
          300: "#E7EDF2",
          400: "#DFE7ED",
          500: "#D7E1E8",
        },
        coral: {
          DEFAULT: "#FF7F7F",
          foreground: "#FFFFFF",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}